### ISSUE TITLE
Bug: Lightning nodes not restarting on subsequent development sessions

### ISSUE THREAD

**Issue by murtyjones** [jamaljsr/polar#410] opened 2020-12-17 03:17 UTC
**Describe the bug**
The `lnd` and `c-lightning` nodes in my session aren't restarting properly when I fire up `yarn dev`.

For `lnd`, the container is panicking with `panic: Unable to synchronize wallet to chain: -8: Block height out of range`

For `c-lightning`, the message is `bitcoind has gone backwards from 173 to 4 blocks!`

**To Reproduce**
Not sure exactly how this is reproduced but I _think_ it happens when the docker instance that's running in the background is stopped between development sessions.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/708562/102439122-a8fdc580-3feb-11eb-8ccd-6522d36ea715.png)
![image](https://user-images.githubusercontent.com/708562/102439141-b4e98780-3feb-11eb-8a27-4ff019e2989d.png)
![image](https://user-images.githubusercontent.com/708562/102439219-db0f2780-3feb-11eb-8de6-ab856b71e677.png)

**Desktop (please complete the following information):**
- OS: macOS Catalina
- Polar Version: master
- Docker Version: 20.10.0
- Docker Compose Version: 1.27.4

**Additional context**

**Comment by jamaljsr** [comment] 2020-12-17 03:35
Hey @murtyjones Ive seen this a bunch of times myself, though I have never been able to track down a root cause. I agree it's got something to do with the docker containers restarting. I've noticed it happens after my machine sleeps or reboots and i forgot to stop the network. 

The workaround I do is simply import or create a new network. This hasn't been too painful for me. In my workflow, I delete & import/create networks multiple times a day. So I haven't been bothered enough investigate any further.

**Comment by murtyjones** [comment] 2020-12-17 11:33
> Hey @murtyjones Ive seen this a bunch of times myself, though I have never been able to track down a root cause. I agree it's got something to do with the docker containers restarting. I've noticed it happens after my machine sleeps or reboots and i forgot to stop the network.
> 
> The workaround I do is simply import or create a new network. This hasn't been too painful for me. In my workflow, I delete & import/create networks multiple times a day. So I haven't been bothered enough investigate any further.

Makes sense! I'll use that workaround. 

I wonder whether or not this is likely to be an issue with the built version of the app, since the docker functionality is bundled

**Comment by jamaljsr** [comment] 2022-08-04 04:12
Going to close this issue now as I don't plan on working on it in the near future.

**Closed by jamaljsr** 2022-08-04 04:12 UTC
Labels: bug
