### ISSUE TITLE
Feature Request: verify developer macOS

### ISSUE THREAD

**Issue by OR13** [jamaljsr/polar#549] opened 2022-04-15 17:35 UTC
**Is your feature request related to a problem? Please describe.**
Fearful of installing anything related to blockchain where this is the message I see from the OS:
![Screen Shot 2022-04-15 at 12 32 58 PM](https://user-images.githubusercontent.com/8295856/163602499-aa6e7f93-bb20-4c23-a841-d3995dd56e27.png)

![Screen Shot 2022-04-15 at 12 39 10 PM](https://user-images.githubusercontent.com/8295856/163603053-dff89549-1840-47c3-8fca-03ac8c508b2e.png)

**Describe the solution you'd like**
Pay apple so that we can all feel safer.

**Additional context**
Deeply sorry to even be requesting this... given the obvious conflict of interest with Apple and Bitcoin  / crypto related products.

**Comment by jamaljsr** [comment] 2022-04-15 19:43
Duplicate of #544 

While I do appreciate the concern about the warning, there is no gain to be had with me creating a developer certificate. Polar uses regtest bitcoin which has no value, so there is never any funds at risk. If you are concerned that the binary you've downloaded may contain malware, I think the better solution is to build it from the source code.

**Closed by jamaljsr** 2022-04-15 19:43 UTC
Labels: enhancement

**Comment by sugarjig** [comment] 2022-10-24 02:28
Hi @jamaljsr. I came across this issue after trying to create a Homebrew Cask for Polar. In the process, I learned that builds must be signed in order to be accepted by Homebrew. That would be one benefit to signing the build. I don't know if that's enough to convince you, but I thought I would bring it up! 😄

**Comment by jamaljsr** [comment] 2022-10-27 05:55
Thanks for sharing this use case. It's not something I'd ever considered. I'll take another look at signing when time permits. But I can't make any promises that I'll implement it.
